### ISSUE TITLE
LimeGlass stole some code from this repository.

### ISSUE THREAD

**Issue by 28andrew** [Podshot/World-War#1]
https://github.com/TheLimeGlass/Skellett/blob/master/src/com/gmail/thelimeglass/SkellettAPI/BlockConstructor.java is extremely similar to your https://github.com/Podshot/World-War/blob/940c394d0f952eaaed81da7c454dadb8a8709694/src/me/astramg/resources/BlockGenerator.java. I would recommend you file a DMCA for copyright infringement.

**Comment by Podshot** [comment]
Despite him not giving proper credit to the original author (I did not originally create that class) by not leaving the original package name, and instead changed it, I won't do anything, since the original author said anyone could copy/use it in their own projects as long as they gave proper credit. Thanks for keeping an eye out for copied code though!
